import {
  MessageSquare,
  History,
  Bot,
  Cpu,
  Terminal,
  Clock,
  Code,
  BookOpen,
  Wrench,
  Boxes,
  Radio,
  Sliders,
  Key,
  Settings,
  FileText,
} from "lucide-react";

export const SIDEBAR_ITEMS = [
  { id: "chat", label: "Chat", icon: MessageSquare, path: "/chat" },
  { id: "sessions", label: "Sessions", icon: History, path: "/sessions" },
  { id: "agents", label: "Agents", icon: Bot, path: "/agents" },
  { id: "models", label: "Models", icon: Cpu, path: "/models" },
  { id: "tasks", label: "Tasks", icon: Clock, path: "/tasks" },
  { id: "skills", label: "Skills", icon: Code, path: "/skills" },
  { id: "knowledge", label: "Knowledge", icon: BookOpen, path: "/knowledge" },
  { id: "tools", label: "Tools", icon: Wrench, path: "/tools" },
  { id: "mcp", label: "MCP", icon: Boxes, path: "/mcp" },
  { id: "channels", label: "Channels", icon: Radio, path: "/channels" },
  { id: "config", label: "Config", icon: Sliders, path: "/config" },
  { id: "keys", label: "Keys", icon: Key, path: "/keys" },
  { id: "system", label: "System", icon: Settings, path: "/system" },
  { id: "logs", label: "Logs", icon: Terminal, path: "/logs" },
  {
    id: "documentation",
    label: "Documentation",
    icon: FileText,
    path: "/documentation",
  },
];
