import datetime
import json
from typing import Generator

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    create_engine,
    event,
)
from sqlalchemy.orm import declarative_base, relationship, sessionmaker

from orcanium.app.core.config import DB_PATH, ensure_orcanium_dirs

ensure_orcanium_dirs()

# SQLite engine setup
SQLALCHEMY_DATABASE_URL = f"sqlite:///{DB_PATH}"
engine = create_engine(
    SQLALCHEMY_DATABASE_URL, connect_args={"check_same_thread": False}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


@event.listens_for(engine, "connect")
def _set_sqlite_pragma(dbapi_connection, connection_record):
    cursor = dbapi_connection.cursor()
    cursor.execute("PRAGMA journal_mode=WAL")
    cursor.execute("PRAGMA busy_timeout=5000")
    cursor.close()


def get_db() -> Generator:
    """Dependency to get database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# --- SQLite Database Models ---


class AgentState(Base):
    __tablename__ = "agent_states"

    name = Column(String, primary_key=True, index=True)
    status = Column(String, default="stopped")  # running, paused, stopped, archived
    active_sessions = Column(Integer, default=0)
    health = Column(String, default="healthy")
    model_provider = Column(String, nullable=True)
    model_name = Column(String, nullable=True)


class Session(Base):
    __tablename__ = "sessions"

    id = Column(String, primary_key=True, index=True)
    agent_name = Column(
        String, ForeignKey("agent_states.name", ondelete="CASCADE"), index=True
    )
    title = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(
        DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow
    )
    archived_at = Column(DateTime, nullable=True)
    total_input_tokens = Column(Integer, default=0)
    total_output_tokens = Column(Integer, default=0)
    source = Column(String, default="api")

    messages = relationship(
        "Message", back_populates="session", cascade="all, delete-orphan"
    )


class Message(Base):
    __tablename__ = "messages"

    id = Column(String, primary_key=True, index=True)
    session_id = Column(
        String, ForeignKey("sessions.id", ondelete="CASCADE"), index=True
    )
    sender = Column(String, nullable=False)  # user, agent, system
    content = Column(Text, nullable=False)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)

    session = relationship("Session", back_populates="messages")


class KnowledgeDocument(Base):
    __tablename__ = "knowledge_documents"

    id = Column(String, primary_key=True, index=True)
    name = Column(String, nullable=False)
    type = Column(String, nullable=False)  # pdf, md, code, web
    path = Column(String, nullable=False)
    status = Column(String, default="pending")  # pending, indexed, failed
    chunk_count = Column(Integer, default=0)

    chunks = relationship(
        "KnowledgeChunk", back_populates="document", cascade="all, delete-orphan"
    )


class KnowledgeChunk(Base):
    __tablename__ = "knowledge_chunks"

    id = Column(String, primary_key=True, index=True)
    doc_id = Column(
        String, ForeignKey("knowledge_documents.id", ondelete="CASCADE"), index=True
    )
    content = Column(Text, nullable=False)
    vector = Column(
        Text, nullable=True
    )  # stored as JSON string of float embedding array
    bm25_tokens = Column(
        Text, nullable=True
    )  # stored as JSON list or space separated tokens

    document = relationship("KnowledgeDocument", back_populates="chunks")

    def get_vector(self) -> list:
        if not self.vector:
            return []
        try:
            return json.loads(self.vector)
        except Exception:
            return []

    def set_vector(self, vec_list: list):
        self.vector = json.dumps(vec_list)


class KnowledgeEntry(Base):
    """Promoted knowledge entry — durable storage for distilled cognitive content.

    Populated by the knowledge promotion pipeline (KnowledgeCandidate → promote → store).
    SQLite is authoritative. Markdown mirror generated by KnowledgeRepository.sync_to_markdown().

    This is separate from KnowledgeChunk (raw document ingestion).
    KnowledgeEntry stores CURATED, PROMOTED knowledge. KnowledgeChunk stores RAW document chunks.
    """

    __tablename__ = "knowledge_entries"

    id = Column(String, primary_key=True, index=True)
    agent_name = Column(String, index=True, nullable=False)
    content = Column(Text, nullable=False)
    category = Column(String, default="OTHER")
    source = Column(String, default="promotion")  # promotion, import, manual
    knowledge_score = Column(Float, default=0.0)
    frequency = Column(Integer, default=1)
    source_diversity = Column(Integer, default=1)
    stability_score = Column(Float, default=0.5)
    utility_score = Column(Float, default=0.5)
    created_at = Column(String, nullable=False)
    updated_at = Column(String, nullable=True)
    tags = Column(Text, nullable=True)  # JSON list




class KnowledgeCandidate(Base):
    """Persistent knowledge candidate — survives restarts, backed by SQLite.

    Created by the Memory Distiller or Review Worker. Must pass the Knowledge
    Validator (4 gates) before being promoted to KnowledgeEntry.
    """

    __tablename__ = "knowledge_candidates"

    id = Column(String, primary_key=True, index=True)
    agent_name = Column(String, index=True, nullable=False)
    content = Column(Text, nullable=False)
    category = Column(String, nullable=False)  # FACT|RULE|REFERENCE|CONCEPT
    confidence = Column(Float, default=0.5)
    evidence_count = Column(Integer, default=1)
    status = Column(String, default="PENDING")  # PENDING|APPROVED|REJECTED|PROMOTED|REVIEWING
    score = Column(Float, default=0.0)
    validation_reason = Column(Text, nullable=True)
    created_at = Column(String, nullable=False)
    updated_at = Column(String, nullable=True)

class TimelineEvent(Base):
    """Persistent event storage for the evidence timeline.

    Populated by TimelineConsumer from event bus emissions.
    Retention: configurable cap (default 5000 events), oldest removed when exceeded.
    NOT a permanent audit log — recent operational evidence only.

    Metadata fields support timeline reconstruction (Phase 5):
        workflow_id       Groups events into logical workflows
        parent_event_id   Enables parent-child hierarchy
    """

    __tablename__ = "timeline_events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(String, nullable=False, index=True)
    category = Column(String, nullable=False, index=True)
    event_name = Column(String, nullable=False, index=True)
    agent_id = Column(String, nullable=True, index=True)
    session_id = Column(String, nullable=True)
    workflow_id = Column(String, nullable=True, index=True)
    parent_event_id = Column(String, nullable=True)
    payload_json = Column(Text, nullable=True)


class TaskExecutionLog(Base):
    """Execution history for scheduled tasks."""

    __tablename__ = "task_execution_logs"

    id = Column(String, primary_key=True, index=True)
    task_id = Column(
        String, ForeignKey("scheduled_tasks.id", ondelete="CASCADE"), index=True
    )
    started_at = Column(DateTime, default=datetime.datetime.utcnow)
    finished_at = Column(DateTime, nullable=True)
    status = Column(String, default="running")  # running, success, failed
    output = Column(Text, nullable=True)
    error = Column(Text, nullable=True)


class ScheduledTask(Base):
    __tablename__ = "scheduled_tasks"

    id = Column(String, primary_key=True, index=True)
    agent_name = Column(
        String, ForeignKey("agent_states.name", ondelete="CASCADE"), index=True
    )
    cron_expr = Column(String, nullable=False)  # cron string e.g. "0 * * * *"
    job_type = Column(
        String, nullable=False
    )  # run_agent, retrieve_news, sync_knowledge
    payload = Column(Text, nullable=True)  # JSON string of args/payload
    next_run = Column(DateTime, nullable=True)
    status = Column(String, default="active")  # active, paused, completed


class ChannelConfig(Base):
    __tablename__ = "channel_configs"

    id = Column(String, primary_key=True, index=True)
    platform = Column(String, nullable=False)  # telegram, discord, etc.
    enabled = Column(Boolean, default=False)
    config = Column(Text, nullable=True)  # JSON string of keys/tokens/creds

    def get_config(self) -> dict:
        if not self.config:
            return {}
        try:
            return json.loads(self.config)
        except Exception:
            return {}

    def set_config(self, cfg_dict: dict):
        self.config = json.dumps(cfg_dict)


class ProviderMetadata(Base):
    __tablename__ = "provider_metadata"

    provider_id = Column(String, primary_key=True, index=True)
    provider_name = Column(String, nullable=False)
    enabled = Column(Boolean, default=True)
    last_checked = Column(DateTime, default=datetime.datetime.utcnow)
    status = Column(String, default="active")  # active, disconnected, error


class AgentRuntimeState(Base):
    """Per-agent learning state — persists nudge counters across restarts."""

    __tablename__ = "agent_runtime_state"

    agent_id = Column(String, primary_key=True, index=True)
    turns_since_memory = Column(Integer, nullable=False, default=0)
    turns_since_skill = Column(Integer, nullable=False, default=0)
    turns_since_user = Column(Integer, nullable=False, default=0)
    last_memory_review = Column(DateTime, nullable=True)
    last_skill_review = Column(DateTime, nullable=True)
    last_user_review = Column(DateTime, nullable=True)
    updated_at = Column(
        DateTime,
        nullable=False,
        default=datetime.datetime.utcnow,
        onupdate=datetime.datetime.utcnow,
    )


class CrossTalkRequest(Base):
    """Durable request between two independent agent runtimes."""

    __tablename__ = "cross_talk_requests"

    id = Column(String, primary_key=True, index=True)
    source_agent_id = Column(String, nullable=False, index=True)
    target_agent_id = Column(String, nullable=False, index=True)
    source_session_id = Column(String, nullable=True)
    target_session_id = Column(String, nullable=True)
    turn_id = Column(String, nullable=True, index=True)
    request_text = Column(Text, nullable=False)
    context_summary = Column(Text, nullable=True)
    status = Column(String, nullable=False, default="pending_permission", index=True)
    result = Column(Text, nullable=True)
    error = Column(Text, nullable=True)
    hop = Column(Integer, nullable=False, default=0)
    expires_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)



def init_db():
    Base.metadata.create_all(bind=engine)
